services:
  cups-airprint:
    container_name: cups-airprint
    image: cups-airprint:latest
    build: .
    restart: always
    network_mode: "host"
    # listens on port 631
    devices:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      #DEBUG: 1
      CUPSADMIN: ${CUPSADMIN}
      CUPSPASSWORD: ${CUPSPASSWORD}
      CUPSMODE: "dnssd"
    volumes:
      - "./services:/services"
      - "./config:/config"    
      - "/var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket"
      - "/etc/localtime:/etc/localtime:ro"
    dns:
      - ${DNS}
    env_file:
      - .env

